DVTrack/Controllers/ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DVTrack.Models;

namespace DVTrack.Controllers
{
    public class ArticlesController : Controller
    {
        private TrackContext db = new TrackContext();

        //
        // GET: /Articles/
        public ActionResult News()
        {
            ViewBag.Message = "Thunder News";
            return View(db.Articles.OrderByDescending(e=>e.PostedDate).Take(3).ToList());
        }

        public ActionResult Index()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("News");
            }
            DateTime _LastYear = DateTime.Today.AddMonths(-12);
            return View(db.Articles.Where(e => e.PostedDate > _LastYear).OrderByDescending(e => e.PostedDate).ToList());
        }

        //
        // GET: /Articles/Details/5

        public ActionResult Details(int id = 0)
        {
            Article article = db.Articles.Find(id);
            if (article == null)
            {
                return HttpNotFound();
            }
            return View(article);
        }

        //
        // GET: /Articles/Create

        public ActionResult Create()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("News");
            }
            return View();
        }

        //
        // POST: /Articles/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Article article)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("News");
            }
            if (ModelState.IsValid)
            {
                article.PostedDate = DateTime.UtcNow.AddHours(-7);
                db.Articles.Add(article);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(article);
        }

        //
        // GET: /Articles/Edit/5

        public ActionResult Edit(int id = 0)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("News");
            }
            Article article = db.Articles.Find(id);
            if (article == null)
            {
                return HttpNotFound();
            }
            return View(article);
        }

        //
        // POST: /Articles/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Article article)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("News");
            }
            if (ModelState.IsValid)
            {
                article.PostedDate = DateTime.UtcNow.AddHours(-7);
                db.Entry(article).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(article);
        }

        //
        // GET: /Articles/Delete/5

        public ActionResult Delete(int id = 0)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("News");
            }
            Article article = db.Articles.Find(id);
            if (article == null)
            {
                return HttpNotFound();
            }
            return View(article);
        }

        //
        // POST: /Articles/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("News");
            }
            Article article = db.Articles.Find(id);
            db.Articles.Remove(article);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

DVTrack/Controllers/CoachesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DVTrack.Models;

namespace DVTrack.Controllers
{
    public class CoachesController : Controller
    {
        private TrackContext db = new TrackContext();

        //
        // GET: /Coaches/
        public ActionResult Staff(string id)
        {
            //switch (id)
            //{
            //    case "sprint":
            //        ViewBag.Message = "Thunder Sprint Coaches";
            //        break;
            //    case "dist":
            //        ViewBag.Message = "Thunder Distance Coaches";
            //        break;
            //    case "vj":
            //        ViewBag.Message = "Thunder Vertical Jumps Coaches";
            //        break;
            //    case "hj":
            //        ViewBag.Message = "Thunder Hortizontal Jumps Coaches";
            //        break;
            //    case "throw":
            //        ViewBag.Message = "Thunder Throwing Coaches";
            //        break;
            //    default:
                    ViewBag.Message = "Thunder Coaches";
            //        break;
            //}

            var filtered = (from all in db.Coaches
                            where all.Active == true
                            orderby all.Head descending, all.Group, all.Title descending, all.Event ascending
                            select all).ToList();
            return View(filtered);
        }


        public ActionResult Index()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Staff");
            }
            return View(db.Coaches.ToList());
        }

        //
        // GET: /Coaches/Details/5

        public ActionResult Details(int id = 0)
        {
            Coach coach = db.Coaches.Find(id);
            if (coach == null)
            {
                return HttpNotFound();
            }
            return View(coach);
        }

        //
        // GET: /Coaches/Create

        public ActionResult Create()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Staff");
            }
            return View();
        }

        //
        // POST: /Coaches/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Coach coach)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Staff");
            }
            if (ModelState.IsValid)
            {
                db.Coaches.Add(coach);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(coach);
        }

        //
        // GET: /Coaches/Edit/5

        public ActionResult Edit(int id = 0)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Staff");
            }
            Coach coach = db.Coaches.Find(id);
            if (coach == null)
            {
                return HttpNotFound();
            }
            return View(coach);
        }

        //
        // POST: /Coaches/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Coach coach)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Staff");
            }
            if (ModelState.IsValid)
            {
                db.Entry(coach).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(coach);
        }

        //
        // GET: /Coaches/Delete/5

        public ActionResult Delete(int id = 0)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Staff");
            }
            Coach coach = db.Coaches.Find(id);
            if (coach == null)
            {
                return HttpNotFound();
            }
            return View(coach);
        }

        //
        // POST: /Coaches/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Staff");
            }
            Coach coach = db.Coaches.Find(id);
            db.Coaches.Remove(coach);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

DVTrack/Controllers/HomeController.cs
using DVTrack.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DVTrack.Controllers
{
    public class HomeController : Controller
    {
        private TrackContext db = new TrackContext();

        //
        // GET: /Articles/

        public ActionResult Index()
        {
            ViewBag.Message = "Thunder Track and Field";

            return View(db.Articles.Where(e => e.ExternalLink == null).OrderByDescending(o => o.PostedDate).Take(3).ToList());
        }

        public ActionResult Calendar()
        {
            return View("Calendar");
        }
    }
}

DVTrack/Views/Home/Index.cshtml
@model IEnumerable<DVTrack.Models.Article>
@{
    ViewBag.Title = "Home of the Thunder";
}



<div class="row">
    <div class="col-md-3">

        <div class="panel panel-primary">

            <div class="panel-heading">
                <h3 class="panel-title">
                    <i class="fa fa-exclamation-circle"></i>
                    Announcements
                </h3>
            </div>
            <ul class="list-group">
                @foreach (var item in Model)
                {
                    if (item.PostedDate > (DateTime.Today.AddDays(-30)))
                    {
                        <a class="list-group-item list-group-item-danger" href='@(Url.Action("Details", "Articles", new { id = item.ArticleId }))'><b>@item.Headline</b></a>
                    }
                    else
                    {
                        <a class="list-group-item" href='@(Url.Action("Details", "Articles", new { id = item.ArticleId }))'>@item.Headline</a>
                    }
                }
            </ul>
        </div>
        <div class="panel panel-primary">

            <div class="panel-heading">
                <h3 class="panel-title">
                    <i class="fa fa-check-square"></i>
                    Pre-Season Checklist
                </h3>
            </div>
            <ul class="list-group">
                @*<li class="list-group-item">Weight Training - Register for Adv PE in January</li>*@
                <a class="list-group-item" href="https://docs.google.com/forms/d/e/1FAIpQLScXp_m-PpEgH6EDPT0FRR09ubtI8SdQIWBPN-j9pjjWV8YEyw/viewform">2020 Code of Conduct</a>
                <a class="list-group-item" href="https://drive.google.com/open?id=1cH8VVq3h8Jmbu2VwYvYfWG455U78QdSq" target="_blank">Volunteer Sign Up</a>
                <a class="list-group-item" href="http://www.registermyathlete.com" target="_blank">Register My Athlete - Deadline 2/7/2020</a>
                <a class="list-group-item" href="http://eepurl.com/bQPz89" target="_blank">Join Our Mailing List - Do this even if you entered your email in the Code of Conduct form!</a>
                <a class="list-group-item" href="@(Url.Action("TrackFees", "Boosters"))" target="_blank">Pay Booster Dues</a>
				<a class="list-group-item" href="https://www.frysfood.com/topic/community-rewards-9" target="_blank">Link Your Fry's Card to Desert Vista Track & Field Boosters</a>
				<a class="list-group-item" href="@(Url.Action("Staff", "Coaches"))">Club Training - Year Round Options. Email Head Coach for More Info</a>
            </ul>
        </div>
    </div>

    <div class="col-md-6">

        <div id="carousel" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">

                @foreach (var imgPath in Directory.GetFiles(Server.MapPath("~/Images/MeetPics/"), "*.jpg").OrderBy(x => Guid.NewGuid()).Select((value, i) => new { i, value }))
                {
                    var img = new FileInfo(imgPath.value);

                    <div class="@Html.DisplayName(imgPath.i == 0 ? "item active" : "item")">
                        <img class="img-responsive center-block rounded-carousel" src="@Url.Content(String.Format("~/Images/MeetPics/{0}", img.Name))" />
                    </div>
                }
            </div>
        </div>
    </div>

    <div class="col-md-3">
        <div class="panel panel-primary panel-group">
            <div class="panel-heading">
                <h3 class="panel-title">
                    <i class="fa fa-bolt"></i>
                    Arizona State Champions
                </h3>
            </div>
            <div class="panel-body">
                <h4>
                    <b><em>Girls:</em> 2004, 1999<br /></b>
                    <br />
                    <b><em>Boys:</em> 2018, 2015, 2009, 2008, 2007</b>
                </h4>
            </div>
            <div class="panel-footer">
                <h5><strong>Runners-Up</strong></h5>
                <em>Girls:</em> 2018, 2017, 2014, 2013, 2010, 2006, 2005, 2003, 2002, 2001<br />
                <br />
                <em>Boys:</em> 2017, 2016, 2014, 2006, 2005
            </div>
        </div>

    </div>
</div>

DVTrack/Views/Home/Staff.cshtml
@model IEnumerable<DVTrack.Models.Coach>

@{
    ViewBag.Title = "Staff";
}

<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title"><span class="glyphicon glyphicon-user" aria-hidden="true"> </span>@ViewBag.Message</h3>
    </div>
    <div class="panel-body">
        <form runat="server">
            <table class="table table-striped table-hover ">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Events</th>
                        <th>Position</th>
                        <th>Email</th>
                    </tr>
                </thead>
                <tbody>
                @foreach (var item in Model)
                {

                    <tr>
                        <td><img src="@item.PhotoSrc" width="80" class="img-circle" />
                            @Html.DisplayFor(modelItem => item.FullName)</td>
                        <td>@Html.DisplayFor(modelItem => item.Event)</td>
                        <td>@Html.DisplayFor(modelItem => item.Title)</td>
                        <td>@Html.DisplayFor(modelItem => item.Email)</td>
                    </tr>
                }
                </tbody>
            </table>
        </form>
    </div>
</div>